# Generated by Django 2.1 on 2019-10-16 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SheetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='_class',
        ),
        migrations.AddField(
            model_name='sheet',
            name='Class',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sheet',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sheet',
            name='fDeathSave1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='fDeathSave2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='fDeathSave3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='sDeathSave1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='sDeathSave2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='sDeathSave3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sCharisma',
            field=models.BooleanField(verbose_name='Saving Throw: Charisma'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sConstitution',
            field=models.BooleanField(verbose_name='Saving Throw: Constitution'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sDexterity',
            field=models.BooleanField(verbose_name='Saving Throw: Dexterity'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sIntelligence',
            field=models.BooleanField(verbose_name='Saving Throw: Intelligence'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sStrength',
            field=models.BooleanField(verbose_name='Saving Throw: Strength'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sWisdom',
            field=models.BooleanField(verbose_name='Saving Throw: Wisdom'),
        ),
        migrations.AddField(
            model_name='item',
            name='sheet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sheets.Sheet'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='sheetGroup',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sheets.SheetGroup'),
        ),
    ]
