# Generated by Django 2.2.5 on 2019-09-21 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_auto_20190921_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='_class',
            new_name='Class',
        ),
    ]
