# Generated by Django 2.1 on 2019-10-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_auto_20191016_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='sheetGroup',
        ),
    ]
