# Generated by Django 2.2.5 on 2019-09-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_auto_20190921_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterSheet', models.CharField(choices=[('foo-baboo', 'Foo Baboo'), ('jenkin-hardegg', 'Jenkin Hardegg'), ('kan-kuranden', 'Kan Kuranden'), ('makkusu', 'Makkusu'), ('mystic', 'Mystic'), ('pap', 'Papak Kravooshi'), ('sancho-the-iii', 'Sancho the III'), ('xyvz', 'Xyvz')], max_length=100)),
                ('attackName', models.CharField(max_length=100)),
                ('attackDamage', models.CharField(max_length=100)),
                ('attackType', models.CharField(choices=[('acid', 'Acid'), ('bludgeoning', 'Bludgeoning'), ('cold', 'Cold'), ('fire', 'Fire'), ('force', 'Force'), ('lightning', 'Lightning'), ('necrotic', 'Necrotic'), ('piercing', 'Piercing'), ('poison', 'Poison'), ('psychic', 'Psychic'), ('radiant', 'Radiant'), ('slashing', 'Slashing'), ('thunder', 'Thunder')], max_length=100)),
            ],
        ),
    ]
