# Generated by Django 2.1 on 2019-10-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_remove_sheet_sheetgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='sheetGroup',
            field=models.ManyToManyField(to='sheets.SheetGroup'),
        ),
    ]
