# Generated by Django 2.1 on 2019-10-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_sheet_sheetgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='sheetGroup',
            field=models.ManyToManyField(blank=True, null=True, to='sheets.SheetGroup'),
        ),
    ]
