# Generated by Django 2.2.5 on 2019-09-23 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_attack'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attack',
        ),
    ]
