# Generated by Django 2.1 on 2019-10-16 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_auto_20191016_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='sheetGroup',
        ),
        migrations.AddField(
            model_name='sheet',
            name='sheetGroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sheets.SheetGroup'),
        ),
    ]
