# Generated by Django 2.2.5 on 2019-09-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_delete_attack'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='attack1Damage',
            field=models.CharField(default='1d6', max_length=100, verbose_name='First attack damage (dice)'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='attack1Name',
            field=models.CharField(default='', max_length=100, verbose_name='First attack name'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='attack1Type',
            field=models.CharField(choices=[('acid', 'Acid'), ('bludgeoning', 'Bludgeoning'), ('cold', 'Cold'), ('fire', 'Fire'), ('force', 'Force'), ('lightning', 'Lightning'), ('necrotic', 'Necrotic'), ('piercing', 'Piercing'), ('poison', 'Poison'), ('psychic', 'Psychic'), ('radiant', 'Radiant'), ('slashing', 'Slashing'), ('thunder', 'Thunder')], default='', max_length=100, verbose_name='First attack type'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='attack2Damage',
            field=models.CharField(default='1d6', max_length=100, verbose_name='Second attack damage (dice)'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='attack2Name',
            field=models.CharField(default='', max_length=100, verbose_name='Second attack name'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='attack2Type',
            field=models.CharField(choices=[('acid', 'Acid'), ('bludgeoning', 'Bludgeoning'), ('cold', 'Cold'), ('fire', 'Fire'), ('force', 'Force'), ('lightning', 'Lightning'), ('necrotic', 'Necrotic'), ('piercing', 'Piercing'), ('poison', 'Poison'), ('psychic', 'Psychic'), ('radiant', 'Radiant'), ('slashing', 'Slashing'), ('thunder', 'Thunder')], default='', max_length=100, verbose_name='Second attack type'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='attack3Damage',
            field=models.CharField(default='1d6', max_length=100, verbose_name='Third attack damage (dice)'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='attack3Name',
            field=models.CharField(default='', max_length=100, verbose_name='Third attack name'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='attack3Type',
            field=models.CharField(choices=[('acid', 'Acid'), ('bludgeoning', 'Bludgeoning'), ('cold', 'Cold'), ('fire', 'Fire'), ('force', 'Force'), ('lightning', 'Lightning'), ('necrotic', 'Necrotic'), ('piercing', 'Piercing'), ('poison', 'Poison'), ('psychic', 'Psychic'), ('radiant', 'Radiant'), ('slashing', 'Slashing'), ('thunder', 'Thunder')], default='', max_length=100, verbose_name='Third attack type'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sCharisma',
            field=models.BooleanField(verbose_name='Saving Throw: Charisma'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sConstitution',
            field=models.BooleanField(verbose_name='Saving Throw: Constitution'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sDexterity',
            field=models.BooleanField(verbose_name='Saving Throw: Dexterity'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sIntelligence',
            field=models.BooleanField(verbose_name='Saving Throw: Intelligence'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sStrength',
            field=models.BooleanField(verbose_name='Saving Throw: Strength'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sWisdom',
            field=models.BooleanField(verbose_name='Saving Throw: Wisdom'),
        ),
    ]
