# Generated by Django 2.1 on 2019-09-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0006_auto_20190923_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='athleticsMod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sheet',
            name='sheetPassword',
            field=models.CharField(default='password', max_length=50, verbose_name='Sheet Password (DO NOT USE A PERSONAL PASSWORD)'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='attack1Type',
            field=models.CharField(choices=[('N/A', 'N/A'), ('acid', 'Acid'), ('bludgeoning', 'Bludgeoning'), ('cold', 'Cold'), ('fire', 'Fire'), ('force', 'Force'), ('lightning', 'Lightning'), ('necrotic', 'Necrotic'), ('piercing', 'Piercing'), ('poison', 'Poison'), ('psychic', 'Psychic'), ('radiant', 'Radiant'), ('slashing', 'Slashing'), ('thunder', 'Thunder')], default='', max_length=100, verbose_name='First attack type'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='attack2Type',
            field=models.CharField(choices=[('N/A', 'N/A'), ('acid', 'Acid'), ('bludgeoning', 'Bludgeoning'), ('cold', 'Cold'), ('fire', 'Fire'), ('force', 'Force'), ('lightning', 'Lightning'), ('necrotic', 'Necrotic'), ('piercing', 'Piercing'), ('poison', 'Poison'), ('psychic', 'Psychic'), ('radiant', 'Radiant'), ('slashing', 'Slashing'), ('thunder', 'Thunder')], default='', max_length=100, verbose_name='Second attack type'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='attack3Type',
            field=models.CharField(choices=[('N/A', 'N/A'), ('acid', 'Acid'), ('bludgeoning', 'Bludgeoning'), ('cold', 'Cold'), ('fire', 'Fire'), ('force', 'Force'), ('lightning', 'Lightning'), ('necrotic', 'Necrotic'), ('piercing', 'Piercing'), ('poison', 'Poison'), ('psychic', 'Psychic'), ('radiant', 'Radiant'), ('slashing', 'Slashing'), ('thunder', 'Thunder')], default='', max_length=100, verbose_name='Third attack type'),
        ),
    ]
