# Generated by Django 2.1 on 2019-10-17 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0007_auto_20191017_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sheet',
            new_name='sht',
        ),
    ]
