# Generated by Django 2.1 on 2019-10-17 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0008_auto_20191017_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sht',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sheets.Sheet'),
        ),
    ]
