# Generated by Django 2.1 on 2019-09-25 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0008_remove_sheet_sheetpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='athleticsMod',
        ),
    ]
