# Generated by Django 2.2.5 on 2019-09-25 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0010_sheet_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='attack1Damage',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='attack1Name',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='attack1Type',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='attack2Damage',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='attack2Name',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='attack2Type',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='attack3Damage',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='attack3Name',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='attack3Type',
        ),
    ]
