# Generated by Django 2.1 on 2019-10-17 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0011_auto_20191017_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('acrobatics', 'Acrobatics'), ('animalHandling', 'Animal Handling'), ('arcana', 'Arcana'), ('athletics', 'Athletics'), ('deception', 'Deception'), ('history', 'History'), ('insight', 'Insight'), ('intimidation', 'Intimidation'), ('investigation', 'Investigation'), ('medicine', 'Medicine'), ('nature', 'Nature'), ('perception', 'Perception'), ('performance', 'Performance'), ('persuasion', 'Persuasion'), ('religion', 'Religion'), ('sleightOfHand', 'Sleight of Hand'), ('stealth', 'Stealth'), ('survival', 'Survival')], default='', max_length=100)),
                ('mod', models.IntegerField()),
                ('sht', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheets.Sheet')),
            ],
        ),
    ]
