# Generated by Django 2.1 on 2019-09-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0011_auto_20190925_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.CharField(choices=[('Clint Highfield', 'Clint Highfield'), ('Foo Baboo', 'Foo Baboo'), ('Jenkin Hardegg', 'Jenkin Hardegg'), ('Kan Kuranden', 'Kan Kuranden'), ('Makkusu', 'Makkusu'), ('Mystic', 'Mystic'), ('Papak Kravooshi', 'Papak Kravooshi'), ('Sancho the III', 'Sancho the III'), ('Xyvz', 'Xyvz'), ('Yan-Flan Zestywill', 'Yan-Flan Zestywill')], default='', max_length=50)),
            ],
        ),
    ]
