# Generated by Django 2.1 on 2019-10-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0012_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='fDeathSave1',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='fDeathSave2',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='fDeathSave3',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sDeathSave1',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sDeathSave2',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sDeathSave3',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
