# Generated by Django 2.1 on 2019-09-30 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0012_attack'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attack',
        ),
    ]
