# Generated by Django 2.2.5 on 2019-10-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0013_auto_20191021_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='fDeathSave2',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='fDeathSave3',
        ),
        migrations.AlterField(
            model_name='sheet',
            name='fDeathSave1',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sDeathSave1',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sDeathSave2',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sDeathSave3',
            field=models.BooleanField(),
        ),
    ]
