# Generated by Django 2.1 on 2019-10-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0014_sheetgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='sheetGroup',
            field=models.CharField(default='', max_length=50),
        ),
    ]
