# Generated by Django 2.1 on 2019-10-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0015_sheet_sheetgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='sheetGroup',
            field=models.CharField(choices=[('dndClub', 'Dungeons and Dragons Club'), ('redend', "Red End's Group")], default='', max_length=50),
        ),
    ]
