# Generated by Django 2.1 on 2019-10-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0016_auto_20191002_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='sheetGroup',
            field=models.CharField(choices=[('Group1', 'Group1')], default='', max_length=50),
        ),
    ]
