# Generated by Django 2.2.5 on 2019-10-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0017_auto_20191002_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='sheetGroup',
            field=models.CharField(choices=[('Group1', 'Group1'), ('Group2', 'Group2')], default='', max_length=50),
        ),
    ]
