# Generated by Django 2.1 on 2019-10-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0019_auto_20191002_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='sheetGroup',
        ),
        migrations.AddField(
            model_name='sheet',
            name='sheetGroup',
            field=models.ManyToManyField(to='sheets.SheetGroup'),
        ),
    ]
