# Generated by Django 2.1 on 2019-10-22 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='')),
                ('Class', models.CharField(default='', max_length=100)),
                ('background', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100)),
                ('xp', models.IntegerField()),
                ('level', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('strengthMod', models.IntegerField()),
                ('dexterityMod', models.IntegerField()),
                ('constitutionMod', models.IntegerField()),
                ('intelligenceMod', models.IntegerField()),
                ('wisdomMod', models.IntegerField()),
                ('charismaMod', models.IntegerField()),
                ('sStrength', models.BooleanField(verbose_name='Saving Throw: Strength')),
                ('sDexterity', models.BooleanField(verbose_name='Saving Throw: Dexterity')),
                ('sConstitution', models.BooleanField(verbose_name='Saving Throw: Constitution')),
                ('sIntelligence', models.BooleanField(verbose_name='Saving Throw: Intelligence')),
                ('sWisdom', models.BooleanField(verbose_name='Saving Throw: Wisdom')),
                ('sCharisma', models.BooleanField(verbose_name='Saving Throw: Charisma')),
                ('otherProficiencies', models.CharField(max_length=250)),
                ('languages', models.CharField(max_length=250)),
                ('copper', models.IntegerField()),
                ('silver', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('platinum', models.IntegerField()),
                ('armorClass', models.IntegerField()),
                ('initiative', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('maxHitPoints', models.IntegerField()),
                ('hitPoints', models.IntegerField()),
                ('hitDice', models.CharField(max_length=250)),
                ('sDeathSave1', models.BooleanField(default=False)),
                ('sDeathSave2', models.BooleanField(default=False)),
                ('sDeathSave3', models.BooleanField(default=False)),
                ('fDeathSave1', models.BooleanField(default=False)),
                ('fDeathSave2', models.BooleanField(default=False)),
                ('fDeathSave3', models.BooleanField(default=False)),
                ('personalityTraits', models.CharField(max_length=250)),
                ('ideals', models.CharField(max_length=250)),
                ('bonds', models.CharField(max_length=250)),
                ('flaws', models.CharField(max_length=250)),
                ('featuresTraits', models.CharField(max_length=250)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SheetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('acrobatics', 'Acrobatics'), ('animalHandling', 'Animal Handling'), ('arcana', 'Arcana'), ('athletics', 'Athletics'), ('deception', 'Deception'), ('history', 'History'), ('insight', 'Insight'), ('intimidation', 'Intimidation'), ('investigation', 'Investigation'), ('medicine', 'Medicine'), ('nature', 'Nature'), ('perception', 'Perception'), ('performance', 'Performance'), ('persuasion', 'Persuasion'), ('religion', 'Religion'), ('sleightOfHand', 'Sleight of Hand'), ('stealth', 'Stealth'), ('survival', 'Survival')], default='', max_length=100)),
                ('mod', models.IntegerField()),
                ('sht', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheets.Sheet')),
            ],
        ),
        migrations.AddField(
            model_name='sheet',
            name='sheetGroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sheets.SheetGroup'),
        ),
        migrations.AddField(
            model_name='item',
            name='sht',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheets.Sheet'),
        ),
    ]
