# Generated by Django 2.2.5 on 2020-04-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_auto_20200402_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='proficiency',
            field=models.IntegerField(default=2),
        ),
    ]
