# Generated by Django 2.2.5 on 2020-04-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0006_sheet_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='level',
            field=models.CharField(choices=[('cantrip', 'Cantrip'), ('infusion', 'Infusion'), ('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th'), ('6', '6th'), ('7', '7th'), ('8', '8th'), ('9', '9th')], default='cantrip', max_length=100),
        ),
    ]
