# Generated by Django 2.2.5 on 2020-04-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0011_spell_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='Type',
            field=models.CharField(choices=[('offensive', 'Offensive'), ('normal', 'Normal')], default='normal', max_length=100),
        ),
    ]
