# Generated by Django 2.2.5 on 2020-05-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0012_auto_20200408_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
