# Generated by Django 2.2.5 on 2020-06-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0013_sheet_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='slug',
        ),
    ]
