# Generated by Django 2.2.5 on 2020-06-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0014_remove_sheet_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.CharField(default='1 gp', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
