# Generated by Django 2.2.5 on 2020-07-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0015_auto_20200605_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='tempHitPoints',
            field=models.IntegerField(default=0),
        ),
    ]
