# Generated by Django 2.2.5 on 2020-07-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0016_sheet_temphitpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='damage',
            field=models.CharField(default='1d6', max_length=7),
        ),
    ]
