# Generated by Django 2.2.5 on 2020-07-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0017_item_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='proficient',
            field=models.BooleanField(default=False),
        ),
    ]
