# Generated by Django 2.2.5 on 2020-07-08 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0019_auto_20200708_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='sht',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheets.Sheet'),
        ),
    ]
